name: Build, Quality, Test

on:
   push:
       branches:
          - develop
          - master
          - QA
          - tma/*
          - fix/*
          - core/*
          - chore/*
          - feature/*
          - format/*
          - docs/*
          - refactor/*
          - ci/*

jobs:
    default:
        container:
            image: node:12-alpine

        runs-on: ubuntu-latest
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Get yarn cache directory path
              id: yarn-cache-dir-path
              run: echo "::set-output name=dir::$(yarn cache dir)"
            - name: Cache modules
              uses: actions/cache@v1.1.2
              id: yarn-cache
              with:
                node-version: '12'
                path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                restore-keys: |
                  ${{ runner.os }}-yarn-
            - name: Install dependencies
              run: yarn
            - name: Lint
              run: yarn lint
            - name: Build
              run: yarn build
            - name: Run tests
              run: yarn test